services:
  postgres:
    image: postgres:15-alpine
    container_name: finfix-postgres
    env_file: ".env" #TODO REMOVE
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in .env}
    ports:
      - "5432:5432" # в проде убрать
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: [finfix-network]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-app}",
        ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:

networks:
  finfix-network:
    driver: bridge
